Library_Managment/Library_Managment/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
path('',include('lm.urls')),
    path('admin/', admin.site.urls),
]

Library_Managment/lm/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='lm'
urlpatterns = [
    path('',views.Index,name ='index'),

    path('user/<int:userid>', views.StudentDetail, name='user'),
    path('book/<int:pk>', views.BookDetail, name='book'),

    path('user/<int:userid>/payable', views.payable, name='payable'),
    path('pendingBooks/',views.PendingBooks.as_view(),name='pendingbooks'),
    path('pendingFines/',views.PendingFines.as_view(),name='pendingfines'),

    path('searchBook', views.searchBook, name='searchbook'),
    path('searchUser', views.searchUser, name='searchuser'),

    path('issuebook/', views.issuee, name='issue'),
    path('return/<int:issue_id>', views.returnbook, name='return'),

    path('Bookform',views.addUserform,name='bookform'),
    path('Userform',views.addBookform,name='userform'),

    path('addUser',views.addUser,name='adduser'),
    path('addBook',views.addBook,name='addbook'),

    path('Create/user',views.userForm,name='createuser'),
    path('Create/book',views.bookForm,name='createbook'),

    path('Alluser' , views.Users.as_view() , name='alluser'),
    path('Allbook', views.Books.as_view() , name='allbook'),

    path('update/user/',views.updateStudent,name='updateuser'),
    path('update/book/',views.updateBook,name='updatebook'),

    path('library_condition',views.status,name='status')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library_Managment/lm/models.py
from django.db import models
from django.shortcuts import reverse
import datetime


class event_year(models.Model):
    year = models.IntegerField(primary_key=True)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(year=datetime.date.today().year)
        return obj


class event_month(models.Model):
    month = models.IntegerField(primary_key=True)
    year = models.ForeignKey(event_year, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.month)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(month=datetime.date.today().month,year = event_year.load())
        return obj


class event_day(models.Model):
    day = models.IntegerField(primary_key=True)
    month = models.ForeignKey(event_month, on_delete=models.CASCADE)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(day=datetime.date.today().day,month=event_month.load())
        return obj


class LibrarySettings(models.Model):
    maxDelayDayStudent = models.IntegerField(default=14)
    maxDelayDayFaculty = models.IntegerField(default=182)
    revenuePerDayStudent = models.IntegerField(default=10)
    revenuePerDayFaculty = models.IntegerField(default=10)
    total_Books = models.IntegerField(default=0,editable=True)
    total_student = models.IntegerField(default=000,editable=True)
    total_staff = models.IntegerField(default=000,editable=True)
    maxBookForStudent = models.IntegerField(default=2)
    maxBookForFaculty = models.IntegerField(default=3)
    total_issued = models.IntegerField(default=0,editable=True)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj


class Student(models.Model):
    name = models.CharField(max_length=30,default=' ',editable=True)
    roll = models.IntegerField(editable=True,primary_key=True)
    image_path = models.ImageField(default='../static/lm/anon.png',editable=True)
    email = models.EmailField(blank=True,editable=True)
    payable_amount = models.IntegerField(default=0,editable=True)
    is_student = models.BooleanField(default=True,editable=True)
    is_active = models.BooleanField(default=True,null=False,editable=True)
    exist = models.BooleanField(default=True)
    bookCount = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('lm:user', kwargs={'userid': self.pk})


class Book(models.Model):
    barcode = models.IntegerField(default=0,primary_key=True,editable=True,)
    classification_number = models.IntegerField(default=0,null=True,blank=True,editable=True)
    currently_issued = models.BooleanField(default=False,editable=True,null=False,blank=False)
    active = models.BooleanField(default=True,editable=True)

    def get_absolute_url(self):
        return reverse('lm:book', kwargs={'pk': self.pk})


class Issue(models.Model):
    user = models.ForeignKey(Student,on_delete=models.CASCADE,null=True)
    book = models.ForeignKey(Book,on_delete=models.CASCADE,null=True,)
    day = models.ForeignKey(event_day,on_delete=models.CASCADE,null=True)
    issue_time = models.DateTimeField(auto_now_add=True,blank=True,editable=True)
    is_returned = models.BooleanField(default=False,editable=True)
    return_time = models.DateTimeField(auto_now_add=False,blank=True,editable=True,null=True)
    paid = models.BooleanField(default=False,editable=True)
    is_late = models.BooleanField(default=False,editable=True)
    mailSend = models.BooleanField(default=False)

Library_Managment/lm/views.py
from django.views import generic
from .models import *
from django.shortcuts import reverse ,render , get_object_or_404
from . import libSetting
from django.http import HttpResponse , HttpResponseRedirect
from django.http.response import Http404
import datetime
from django.core.files.storage import FileSystemStorage


sett = LibrarySettings.load()


class information():
    def __init__(self, issuee, dayLeft):
        self.issue = issuee
        self.dayLeft = dayLeft


def issueThis(request,userpk,bookpk):
    try :
        user = get_object_or_404(Student,pk = userpk)
        book = get_object_or_404(Book, pk=bookpk)
        if book.currently_issued:
            return HttpResponseRedirect(reverse('lm:book',kwargs={'pk':book.pk}))
        if user.bookCount >= (sett.maxBookForStudent if user.is_student else sett.maxBookForFaculty):
            return StudentDetail(request,user.pk,context={'error':'Already Have Books'})
        if not user.exist :
            return StudentDetail(request, user.pk, context={'error': 'User left Colledge'})
        if not book.active:
            return StudentDetail(request, user.pk, context={'error': 'Book is not active'})
    except Http404:
        return HttpResponse(render(request,'lm/error.html',context={'error':"can't issue book problem occured "}))
    else :
        iss = Issue(user = user,book = book ,day = event_day.load() ,is_returned = False )
        days = sett.maxDelayDayStudent if user.is_student else sett.maxDelayDayFaculty
        book.currently_issued = True
        iss.issue_time = datetime.datetime.now()
        iss.return_time = iss.issue_time.date() + datetime.timedelta(days=days)
        user.bookCount += 1
        user.save()
        book.save()
        iss.save()

        sett.total_issued += 1
        sett.save()
        return HttpResponseRedirect(reverse('lm:user',kwargs={'userid':user.pk}))


def issuee(request):
    print(request.POST)
    dic = request.POST
    userpk = -1
    bookpk = -1
    try :
        userpk = dic.get('userpk') if 'userpk' in dic else get_object_or_404(Student,roll=dic.get('userroll')).pk if 'userroll' in dic else -1
        bookpk = dic.get('bookpk') if 'bookpk' in dic else get_object_or_404(Book,barcode=dic.get('barcode')).pk if 'barcode' in dic else get_object_or_404(Book,barcode=dic.get('barcode')).pk if 'barcode' in dic else -1
    except Http404:
        if userpk == -1:
            return HttpResponse(
                render(request, 'lm/error.html', context={'error': 'user does not exist', 'createUser': True}))
        if bookpk == -1:
            return HttpResponse(render(request, 'lm/error.html', context={'error': 'book does not exist', 'createBook': True}))
    else :
        if userpk == -1:
            return HttpResponse(
                render(request, 'lm/error.html', context={'error': 'user does not exist', 'createUser': True}))
        if bookpk == -1:
            return HttpResponse(
                render(request, 'lm/error.html', context={'error': 'book does not exist', 'createBook': True}))
        return issueThis(request, userpk, bookpk)


def returnbook(request,issue_id):
    info = Issue.objects.get(pk = issue_id)
    book = info.book
    user = info.user
    if not info.is_returned:
        context = {'issue': info}
        delayedby = libSetting.daysLeft(info) - libSetting.getday(info.user.is_student)
        if delayedby > 0:
            context['showDate'] = True
            user.payable_amount += delayedby * libSetting.getcost(info.user.is_student)
            user.save()
        info.is_returned = True
        info.return_time = datetime.datetime.now()
        book.currently_issued = False
        user.bookCount -= 1
        if user.bookCount < 0:
            user.bookCount = 0
        user.save()
        info.save()
        book.save()
        sett.total_issued -= 1
        sett.save()
    return HttpResponseRedirect(reverse('lm:user',kwargs={'userid':user.pk}))


def searchBook(request):
    id = request.POST.get('book')
    try :
        book = get_object_or_404(Book,barcode = id)
    except Http404:
        return HttpResponse(render(request,'lm/error.html', context={'error':"book does not exist"}))
    else :
        return HttpResponseRedirect(reverse('lm:book', kwargs={'pk': book.pk}))


def searchUser(request):
    id = request.POST.get('user')
    try :
        user = get_object_or_404(Student,roll = id)
    except Http404:
        return HttpResponse(render(request,'lm/error.html', context={'error': "User does not exist"}))
    else :
        return HttpResponseRedirect(reverse('lm:user', kwargs={'userid': user.pk}))


def StudentDetail(request,userid,context={}):
    try :
        stud = get_object_or_404(Student,pk = userid)
    except Http404:
        #404 error
        pass
    else:

            books = [information(b, libSetting.daysLeft(b)) for b in stud.issue_set.all().filter(is_returned=False)]
            context['books'] = books
            context['student'] = stud
            return render(request,'lm/userDetail.html',context)


def payable(request,userid):
    student = Student.objects.get(pk=userid)
    all=[information(a,libSetting.daysLeft(a)) for a in student.issue_set.all() if a.is_returned and libSetting.daysLeft(a)>libSetting.getday(a.user.is_student) ]
    return HttpResponse(render(request,'lm/payable.html',context={'issuesday':all,'name':student.name,'roll':student.roll}))


def Index(request):
    return HttpResponse(render(request,'lm/index.html',context={'user':False}))


def userForm(request):
    return HttpResponse(render(request,'lm/userForm.html'))


def bookForm(request):
    return HttpResponse(render(request, 'lm/bookForm.html'))

def addUserform(request):
    return HttpResponse(render(request,'lm/userForm.html'))


def addBookform(request):
    return HttpResponse(render(request,'lm/bookForm.html'))


def addUser(request):
    try :
        dic = request.POST
        print(dic)
        name = dic.get('name') if 'name' in dic else ''
        roll = dic.get('roll')
        email = dic.get('email')
        student = False if 'isstudent'in dic and 'off'== dic.get('isstudent')  else True
        active = False if 'isactive'in dic and 'off'== dic.get('isactive')  else True
        exist = False if 'exist'in dic and 'off'== dic.get('exist')  else True

        s=get_object_or_404(Student,roll=roll)
        return StudentDetail(request,userid=s.pk,context={'error':'user already exists'})
    except Http404:
        s = Student(name=name, roll=roll, email=email, is_student=student, is_active=active, exist=exist,bookCount=0, payable_amount=0)
        if request.FILES and request.FILES['image']:
            image = request.FILES['image']
            fs = FileSystemStorage()
            filename = fs.save(str(s.roll), image)
            uploaded_file_url = fs.url(filename)
            s.image_path = uploaded_file_url
        s.save()
        if student:
            sett.total_student += 1
        else:
            sett.total_staff += 1
        return HttpResponseRedirect(reverse('lm:user',kwargs={'userid':s.pk}))
    except :
        return HttpResponse(render(request,'lm/error.html',context={'error':'Cant create Profile'}))



def addBook(request):
    try :
        dic = request.POST
        print(dic)
        barcode = int(dic.get('barcode'))

        classification_number = dic.get('classification_number') if 'classification_number' in dic else 0
        if not classification_number:
            classification_number=0
        active = False if 'isactive'in dic and 'off'== dic.get('isactive')  else True

        s=get_object_or_404(Book,barcode=barcode)
        return HttpResponseRedirect(reverse('lm:book',kwargs={'pk':s.pk}))
    except :
        s = Book(barcode=barcode,classification_number=classification_number)
        s.save()
        sett.total_Books += 1
        sett.save()
        return HttpResponseRedirect(reverse('lm:book',kwargs={'pk':s.pk}))


class PendingBooks(generic.ListView):
    template_name = 'lm/pendingIssue.html'

    def get_queryset(self):
        return Issue.objects.all().filter(is_returned = False)


class PendingFines(generic.ListView):
    template_name = 'lm/pendingFines.html'
    context_object_name = 'pendingIssue'

    def get_queryset(self):
        return [information(b,libSetting.daysLeft(b)) for b in Issue.objects.all().filter(is_returned = True) if libSetting.daysLeft(b) > libSetting.getday(b.user.is_student) ]


def BookDetail(request,pk,context={}):
    try:
        b=get_object_or_404(Book,pk=pk)
    except Http404:
        return HttpResponse(render(request, 'lm/error.html', context={'error': 'Book does not exist'}))
    else:
        context['book'] = b
        return HttpResponse(render(request,'lm/bookDetail.html',context))


def status(request):
    return render(request,'lm/status.html',context={'sett':sett})



def updateStudent(request):
    dic = request.POST
    try :
        print(dic)
        roll = dic.get('roll')
        s=get_object_or_404(Student,pk=roll)
        stud = s.is_student
        name = dic.get('name') if 'name' in dic else ''
        if name:
            s.name = name

        if request.FILES and request.FILES['image']:
            image = request.FILES['image']
            fs = FileSystemStorage()
            filename = fs.save(str(s.roll), image)
            uploaded_file_url = fs.url(filename)
            s.image_path = uploaded_file_url

        email = dic.get('email') if 'email' in dic else ''
        if email:
            s.email = email
        is_student = True if 'isstudent' in dic and 'on'==dic.get('isstudent') else False

        s.is_student = is_student
        is_active = True if 'isactive' in dic and 'on'==dic.get('isactive') else False

        s.is_active = is_active
        s.save()
        if stud and not s.is_student:
            sett.total_student -= 1
            sett.total_staff += 1
            sett.save()
        if not stud and s.is_student:

Library_Managment/lm/templates/lm/allUsers.html
{% extends 'lm/base.html' %}


{%block title %}Books{% endblock %}

{% block body %}



<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<input class="form-control" id="myInput" type="text" placeholder="Search..">
  <br>


<table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Roll</th>
        <th>Email</th>
          <th>Status</th>
          <th>Book Count</th>
          <th></th>
      </tr>
    </thead>
     <tbody id="myTable" >


     {% for u in object_list %}

      <tr>
          <td>{{u.name }}</td>
          <td><a href="{% url 'lm:user' u.pk %}" >{{u.roll }}</a></td>
          <td>{{ u.email }}</td>
          <td>{%if u.is_active %}Active{%else%}Deactivated{%endif%}</td>
          <td>{{ u.bookCount }}</td>
          <td>{%if u.is_student %}Student{% else %}Faculty{% endif %}</td>
      </tr>
{% endfor %}



     </tbody>
</table>
















{% endblock %}

Library_Managment/lm/templates/lm/bookCard.html
{% load static %}
    <div class="card" style="width:50%;">
  <img class="card-img-top" src="../static/lm/singlebook.png" alt="Card image" style="width:100%;margin-bottom:2">
  <div class="card-body">
    <h3 class="card-title" style="margin-top:0;">{{book.barcode}}</h3>
    {% if book.active %}
      <h4 style="color:green" >Active</h4>
      {% else %}
      <h4 style="color:red" >DeActivated</h4>
      {% endif %}

            <div class="row">


  <div class="col" data-toggle="modal" data-target="#edit">
    <img class="btn btn-primary" src="{% static 'svg/tools.svg' %}">
  </div>


  <div class="modal" id="edit">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Edit {{ book.barcode }}</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="card-body">
            <form class="form-signin" action="{% url 'lm:updatebook' %}" method="post" >
              {% csrf_token %}

              <div class="form-label-group">
                <input name="barcode"  value="{{ book.barcode }}" type="hidden" contenteditable="false" ></input>
              </div>


              <!--div class="form-label-group">
                <input type="number" min="10000" max="999999" value={{ book.classification_number }} name="classification_number" id="inputclassification_number" class="form-control" placeholder="Classification" >
                <label for="inputclassification_number">Classification</label>
              </div-->

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" name="isactive" class="custom-control-input" {% if book.active%}checked="checked"{%endif%} id="customCheck1">
                <label class="custom-control-label"  for="customCheck1">Active</label>

                <!-- body over here -->

              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Update</button>
            </form>
          </div>

        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>


    </div>
  </div>
</div>


</div>
{% if book.active  %}
  <div class="col" data-toggle="modal" data-target="#addb">
    <img class="btn btn-primary" src="{% static 'svg/diff-added.svg' %}">
  </div>


  <div class="modal" id="addb">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Issue Book</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <form  action="{% url 'lm:issue' %}" method="post" >
              {% csrf_token %}

              <input type="hidden"  name="bookpk" value="{{ book.pk }}" ></input>
              <input class="form-control mr-sm-2" type="number" required="required" autofocus="autofocus" maxlength="7" name="userroll" placeholder="Roll number" >

          </form>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>



      {% endif %}

                <div class="col" >
    {% if book.active %} <img src="{% static 'svg/check.svg' %}">

      {% else %}  <img src="{% static 'svg/circle-slash.svg' %}">
      {% endif %}
 </div>

</div>






  <!-- The Modal -->


  </div>

    </div>

Library_Managment/lm/templates/lm/bookDetail.html
{% extends 'lm/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}

<div class="row">

<df class="col">

    {% include 'lm/bookCard.html' %}


</df>


    <div class="col">



<table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Roll</th>
        <th>Issue Date</th>
        <th>return</th>
      </tr>
    </thead>
     <tbody id="myTable" >


     {% for issue in book.issue_set.all %}
{% if not issue.is_returned %}
      <tr>
          <td>{{issue.user.name }}</td>
          <td><a href="{% url 'lm:user' issue.user.pk %}" >{{issue.user.roll }}</a></td>
          <td>{{issue.issue_time }}</td>
        <td>{{ issue.is_returned }}</td>
        <td><a href="{% url 'lm:return' issue.pk %}" class="btn btn-primary">Return</a></td>
      </tr>
     {% endif %}
{% endfor %}



     </tbody>
</table>


    </div>


</div>

{% endblock %}

Library_Managment/lm/templates/lm/issue_list.html
{% extends 'lm/base.html' %}

{% block title %}index page title{% endblock %}


{% block body %}

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<input class="form-control" id="myInput" type="text" placeholder="Search..">
  <br>

 <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Roll</th>
        <th>Book ID</th>
        <th>Issue Date</th>
        <th>Return Status</th>
      </tr>
    </thead>
     <tbody id="myTable" >
{% for issue in pendingIssue %}

      <tr>
          <td>{{issue.user.name }}</td>
          <td><a href="{% url 'lm:user' issue.user.pk %}" >{{issue.user.roll }}</a></td>
          <td><a href="{% url 'lm:book' issue.book.pk %}" >{{issue.book.identity }}</a></td>
        <td>{{issue.issue_time }}</td>
        <td>{{issue.is_returned }}</td>
      </tr>
{% endfor %}

     </tbody>
  </table>

{% endblock %}

Library_Managment/lm/templates/lm/payable.html
{% extends 'lm/base.html' %}

{% block title %}index page title{% endblock %}


{% block body %}
<h3>{{ name }} {{  roll }}</h3>

<table class="table table-bordered">
    <thead>
      <tr>
        <th>Book ID</th>
        <th>Issue Date</th>
        <th>Return Time</th>
        <th>Late By</th>
      </tr>
    </thead>
     <tbody id="myTable" >
{% for iss in issuesday %}

      <tr>
          <td><a href="{% url 'lm:book' iss.issue.book.pk %}" >{{iss.issue.book.barcode }}</a></td>
        <td>{{iss.issue.issue_time }}</td>
        <td>{{iss.issue.return_time }}</td>
        <td>{{iss.dayLeft }}</td>
      </tr>
{% endfor %}

     </tbody>
  </table>

{% endblock %}

Library_Managment/lm/templates/lm/returnn.html
this is returnnn

{{ showDate }}

{{ issue }}

Library_Managment/lm/templates/lm/status.html
{% extends 'lm/base.html' %}

{% block body %}

<table class="table table-bordered" >
<tr><th>Total Books  </th><td>{{sett.total_Books}}</td></tr>
<tr><th>Total Students  </th><td>{{sett.total_student}}</td></tr>
<tr><th>Total Staff </th><td>{{sett.total_staff}}</td></tr>

<tr><th>Current Issues   </th><td>{{sett.total_issued}}</td></tr>

</table>

{% endblock  %}

Library_Managment/lm/templates/lm/userCard.html
{% load static %}
    <div class="card" style="width:50%;">
  <img class="card-img-top" src="{{student.image_path}}" alt="Card image" style="width:100%;margin-bottom:2">
  <div class="card-body">
    <h3 class="card-title" style="margin-top:0;">{{student.name}}</h3>
    {% if not student.exist %}
      <h5 style="color:red">Left College</h5>
    {% endif %}
    <h4 style="color:red" >{% if not student.is_active %}Deactivated{% endif %}</h4>
    <h5>Roll {{student.roll}}</h5>
    {% if student.payable_amount %}<h5>Fine</h5>{% if student.payable_amount %}<a href="{% url 'lm:payable' student.pk %}"><h4> {{student.payable_amount}}</h4></a>
      {% else %}<h4>0</h4>{% endif %}{% endif %}
<h5>Book  {{student.bookCount}}</h5>

            <div class="row">


  <div class="col" data-toggle="modal" data-target="#edit">
    <img class="btn btn-primary" src="{% static 'svg/tools.svg' %}">
  </div>


  <div class="modal" id="edit">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Edit Profile</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="card-body">
            <h5 class="card-title text-center">Update User</h5>
            <form enctype="multipart/form-data" class="form-signin" action="{% url 'lm:updateuser' %}" method="post" >
              {% csrf_token %}

              <div class="form-label-group">
                <input type="hidden" name="roll" value="{{ student.roll }}" id="inputroll" class="form-control" >
                  <label for="inputroll">{{ student.roll }}</label>
              </div>


               <div class="form-label-group">
                <input  name="name" value="{{ student.name }}" type="text" id="inputname" class="form-control" placeholder="Name"  autofocus="">
                  <label for="inputname">Name</label>
              </div>



              <div class="form-label-group">
                <input type="email" name="email" value="{{ student.email }}" id="inputEmail"  class="form-control" placeholder="Email address" >
                <label for="inputEmail">Email address</label>
              </div>


              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" name="isstudent" {% if student.is_student %} checked="checked"{%endif%} class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Student</label>
              </div>

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" name="isactive" {% if student.is_active %} checked="checked"{%endif%} class="custom-control-input" id="customCheck2">
                <label class="custom-control-label" for="customCheck2">Active</label>
              </div>

              <div class="form-label-group">
                <input name="image" type="file" accept="image/*" id="inputImage" class="form-control" placeholder="Image"  autofocus="">
                 <label for="inputImage">Image</label>
              </div>


              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Update</button>
            </form>
          </div>

        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>


            {% if student.is_active and student.exist %}


  <div class="col" data-toggle="modal" data-target="#addb">
    <img class="btn btn-primary" src="{% static 'svg/diff-added.svg' %}">
  </div>


  <div class="modal" id="addb">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Issue Book</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <form  action="{% url 'lm:issue' %}" method="post" >
              {% csrf_token %}

              <input type="hidden"  name="userpk" value="{{ student.pk }}" ></input>
              <input class="form-control mr-sm-2" type="number" required="required" autofocus="autofocus" maxlength="7" name="barcode" placeholder="Book ID" >

          </form>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>



      {% endif %}
          <div class="col" >
    {% if student.is_active %} <img  src="{% static 'svg/check.svg' %}">
      {% else %}  <img src="{% static 'svg/circle-slash.svg' %}">
      {% endif %}
  </div>

</div>






  <!-- The Modal -->


  </div>

    </div>

Library_Managment/lm/templates/lm/userDetail.html
{% extends 'lm/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}

<div class="row">

<div class="col">

    {% include 'lm/userCard.html' %}


</div>





  <div class="col">

<table class="table table-bordered">
    <thead>
      <tr>
        <th>Book ID</th>
        <th>Issue Date</th>
        <th>Days Left</th>
      </tr>
    </thead>
     <tbody id="myTable" >


     {% for issue in books %}

      <tr>
          <td><a href="{% url 'lm:book' issue.issue.book.pk %}" >{{issue.issue.book.barcode }}</a></td>
          <td>{{issue.issue.issue_time }}</td>
          <td>{{issue.dayLeft}}</td>
        <td>{{ issue.is_returned }}</td>
        <td><a href="{% url 'lm:return' issue.issue.pk %}" class="btn btn-primary">Return</a></td>
      </tr>
{% endfor %}



     </tbody>
</table>

  </div>

</div>

{% endblock %}